name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        docker-compose build
        docker-compose run web test.py
  
    

    - name: Push to Docker Hub
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/${{vars.DOCKER_IMAGE_NAME}}
        docker push ${{secrets.DOCKER_USERNAME}}/${{vars.DOCKER_IMAGE_NAME}}:latest

  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{secrets.AZURE_CLIENT_ID}} -p ${{secrets.AZURE_CLIENT_SECRET}} --tenant ${{secrets.AZURE_TENANT_ID}}
        az account set --subscription <subscription-id>


    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      run: terraform apply -auto-approve

    - name: Cleanup
      run: terraform destroy -auto-approve